version: '3.3'

services:
  nginx:
    build: ./requerements/nginx
    container_name: ngnix
    ports:
      - "80:80"
  
  mariadb:
    build: ./requerements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
