version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: ngnix
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - "wordpress-data:/var/www/html/"
    env_file:
      - .env
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - "wordpress-data:/var/www/html/"
    env_file:
      - .env
  adminer:
    image: adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    env_file:
      - .env
  site:
    image: site
    build: ./requirements/bonus/site
    container_name: site
    ports:
      - "5000:5000"

  redis:
    image: redis
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  ftp:
    image: ftp
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "4500:4500"
    env_file:
      - .env

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/yahya/data/wordpress
      o: bind
  mariadb-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/yahya/data/mariadb
      o: bind