version: '3.3'

services:
  nginx:
    build: ./requerements/nginx
    container_name: ngnix
    ports:
      - "80:80"
      - "3001:3001"
  
  mariadb:
    build: ./requerements/mariadb
    container_name: mariadb
