version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: ngnix
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - "wordpress-data:/var/www/html/"
    env_file:
      - .env
    networks:
      - default-net
    restart: on-failure
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    env_file:
      - .env
    networks:
      - default-net
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - "wordpress-data:/var/www/html/"
    env_file:
      - .env
    networks:
      - default-net
    restart: on-failure
  
  adminer:
    image: adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - default-net
    restart: on-failure

  site:
    image: site
    build: ./requirements/bonus/site
    container_name: site
    ports:
      - "5000:5000"
    networks:
      - default-net
    restart: on-failure

  redis:
    image: redis
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - default-net
    restart: on-failure

  ftp:
    image: ftp
    build: ./requirements/bonus/ftp
    container_name: ftp
    volumes:
      - "ftp-data:/home/"
    ports:
      - "21:21"
    env_file:
      - .env
    networks:
      - default-net
    restart: on-failure

  cadvisor:
    image: cadvisor
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "2000:2000"
    env_file:
      - .env
    networks:
      - default-net
    restart: on-failure

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/yahya/data/wordpress
      o: bind
  mariadb-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/yahya/data/mariadb
      o: bind
  ftp-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/yahya/data/ftp
      o: bind

networks:
  default-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.198.128.0/24