FROM debian:buster

WORKDIR /var/www/html/

RUN chmod -R 777 /var/www/html

RUN mkdir /run/php/

COPY ./tools .

RUN chmod +x ./script.sh

RUN apt update

RUN apt install -y php7.3 php-mysqli mariadb-client php-fpm wget

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

RUN chmod +x wp-cli.phar

RUN mv wp-cli.phar /usr/local/bin/wp

RUN wp core download --allow-root

CMD [ "./script.sh" ]
