FROM debian:buster

WORKDIR /var/www/html/

RUN chmod -R 777 /var/www/html

RUN mkdir /run/php/

COPY ./tools .

RUN chmod +x ./script.sh

RUN apt update

RUN apt install -y php7.3 php-mysqli mariadb-client php-fpm wget

CMD [ "./script.sh" ]
