FROM alpine

RUN apk update

RUN apk add nginx

RUN apk add openrc

COPY ./tools/script.sh .

RUN chmod +x ./script.sh

COPY ./tools/index.html /usr/share/nginx/html/

COPY ./tools/default.conf /etc/nginx/http.d/

CMD [ "./script.sh" ]
