FROM alpine

RUN apk update

RUN apk add nginx

RUN apk add openrc

COPY ./tools/script.sh .

RUN chmod +x ./script.sh

COPY ./tools/index.html /usr/share/nginx/html/

COPY ./tools/default.conf /etc/nginx/http.d/

RUN mkdir -p /etc/ssl/private

RUN chmod 700 /etc/ssl/private

RUN apk add openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com"

CMD [ "./script.sh" ]
